/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodRouteImport } from './routes/method'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as RankRouteImport } from './routes/rank'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as PoolMonthRouteImport } from './routes/pool.month'
import { Route as PoolYearRouteImport } from './routes/pool.year'
import { Route as StockCodeRouteImport } from './routes/stock.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolMonthRoute = PoolMonthRouteImport.update({
  id: '/pool/month',
  path: '/pool/month',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolYearRoute = PoolYearRouteImport.update({
  id: '/pool/year',
  path: '/pool/year',
  getParentRoute: () => rootRouteImport,
} as any)
const StockCodeRoute = StockCodeRouteImport.update({
  id: '/stock/$code',
  path: '/stock/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/news': typeof NewsRoute
  '/plan': typeof PlanRoute
  '/quotes': typeof QuotesRoute
  '/rank': typeof RankRoute
  '/watch': typeof WatchRoute
  '/pool/month': typeof PoolMonthRoute
  '/pool/year': typeof PoolYearRoute
  '/stock/$code': typeof StockCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/news': typeof NewsRoute
  '/plan': typeof PlanRoute
  '/quotes': typeof QuotesRoute
  '/rank': typeof RankRoute
  '/watch': typeof WatchRoute
  '/pool/month': typeof PoolMonthRoute
  '/pool/year': typeof PoolYearRoute
  '/stock/$code': typeof StockCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/news': typeof NewsRoute
  '/plan': typeof PlanRoute
  '/quotes': typeof QuotesRoute
  '/rank': typeof RankRoute
  '/watch': typeof WatchRoute
  '/pool/month': typeof PoolMonthRoute
  '/pool/year': typeof PoolYearRoute
  '/stock/$code': typeof StockCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/method'
    | '/news'
    | '/plan'
    | '/quotes'
    | '/rank'
    | '/watch'
    | '/pool/month'
    | '/pool/year'
    | '/stock/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/method'
    | '/news'
    | '/plan'
    | '/quotes'
    | '/rank'
    | '/watch'
    | '/pool/month'
    | '/pool/year'
    | '/stock/$code'
  id:
    | '__root__'
    | '/'
    | '/method'
    | '/news'
    | '/plan'
    | '/quotes'
    | '/rank'
    | '/watch'
    | '/pool/month'
    | '/pool/year'
    | '/stock/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodRoute: typeof MethodRoute
  NewsRoute: typeof NewsRoute
  PlanRoute: typeof PlanRoute
  QuotesRoute: typeof QuotesRoute
  RankRoute: typeof RankRoute
  WatchRoute: typeof WatchRoute
  PoolMonthRoute: typeof PoolMonthRoute
  PoolYearRoute: typeof PoolYearRoute
  StockCodeRoute: typeof StockCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/month': {
      id: '/pool/month'
      path: '/pool/month'
      fullPath: '/pool/month'
      preLoaderRoute: typeof PoolMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/year': {
      id: '/pool/year'
      path: '/pool/year'
      fullPath: '/pool/year'
      preLoaderRoute: typeof PoolYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$code': {
      id: '/stock/$code'
      path: '/stock/$code'
      fullPath: '/stock/$code'
      preLoaderRoute: typeof StockCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodRoute: MethodRoute,
  NewsRoute: NewsRoute,
  PlanRoute: PlanRoute,
  QuotesRoute: QuotesRoute,
  RankRoute: RankRoute,
  WatchRoute: WatchRoute,
  PoolMonthRoute: PoolMonthRoute,
  PoolYearRoute: PoolYearRoute,
  StockCodeRoute: StockCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
